apiVersion: v1
kind: Service
metadata:
  name: frontend-nginxapp-nodeport-service
  labels:
    app: frontend-nginxapp
spec:
  type: NodePort
  selector:
    app: frontend-nginxapp            # reference to (pod) template in frontend deployment
  ports:
    - name: http 
      port:  80
      targetPort: 80
      nodePort: 31237

