apiVersion: apps/v1

kind: Deployment
metadata:
  name: frontend-nginxapp
  labels:
    app: frontend-nginxapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nginxapp
  template:                       #pod
    metadata:
      labels:
        app: frontend-nginxapp
        tier: frontend
    spec:
      containers:
      - name: frontend-app-container
        image: stacksimplify/kube-frontend-nginx:1.0.0
        ports:
          - containerPort: 80

        
