apiVersion: v1
kind: Pod
metadata:         #dictionary
  name: myapp-pod
  labels:
    app: myapp
    tier: frontend
spec:
  containers:     #list
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
        


